version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: ev_route_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neondb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ev_route_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ev_route_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/neondb
      - REDIS_URL=redis://redis:6379/0
      - REDIS_TOKEN=dummy_token
      - GROQ_API_KEY=dummy_key
      - ORS_API_KEY=dummy_key
    depends_on:
      - db
      - redis

volumes:
  pgdata:
